### ISSUE TITLE
V 11 Day routes - Expected Singleton

### ISSUE THREAD

**Issue by sapentia** [OCA/field-service#187]
Hi

testing the v11 verison on a clean install ubuntu 16.04. 
create 2 orders. 
create a day route record
add first to the day route, ok
attempt to add second one to Day Routes record. I get a 'expected singleton' error. 
is this an issue or just not completed yet?

**Comment by brian10048** [comment]
This is an issue.  I have duplicated the error by following similar steps.

Here is the traceback received when attempting to Save the Day Route. 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/field-service/fieldservice/models/fsm_route.py", line 32, in create
    return super(FSMRoute, self).create(vals)
  File "/opt/odoo/odoo11/odoo/models.py", line 3373, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/odoo11/odoo/models.py", line 3520, in _create
    field.write(self.with_context(rel_context), vals[name], create=True)
  File "/opt/odoo/odoo11/odoo/fields.py", line 2302, in write
    comodel.browse(act[2]).write({inverse: record.id})
  **File "/opt/odoo/field-service/fieldservice/models/fsm_order.py", line 203, in write
    vals['customer_id'] = self.location_id.customer_id.id**
  File "/opt/odoo/odoo11/odoo/fields.py", line 935, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo11/odoo/models.py", line 4367, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: fsm.order(43, 13066)

**Comment by kittiu** [comment]
@max3903 I got the exact same error on same test on v12 too.
