### ISSUE TITLE
Deploy in Odoo.sh V11

### ISSUE THREAD

**Issue by DatenSAS** [OCA/field-service#310]
I get this error

2019-08-16 23:33:42,947 14 ERROR datensas-fieldservice11-app-fieldservice-stock-538725 odoo.sql_db: bad query: b'\n CREATE EXTENSION postgis;\n CREATE EXTENSION postgis_topology;\n '
ERROR: could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory

2019-08-16 23:33:42,952 14 WARNING datensas-fieldservice11-app-fieldservice-stock-538725 odoo.modules.loading: Transient module states were reset
2019-08-16 23:33:42,954 14 ERROR datensas-fieldservice11-app-fieldservice-stock-538725 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
File "/home/odoo/src/user/base_geoengine/geo_db.py", line 32, in init_postgis
""")
File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
res = self._obj.execute(query, params)
psycopg2.OperationalError: could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 380, in load_modules
loaded_modules, update_module, models_to_check)
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
perform_checks=perform_checks, models_to_check=models_to_check
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 144, in load_module_graph
getattr(py_module, pre_init)(cr)
File "/home/odoo/src/user/base_geoengine/geo_db.py", line 35, in init_postgis
"Error, can not automatically initialize spatial postgis support. "
odoo.exceptions.MissingError: ('Error, can not automatically initialize spatial postgis support. Database user may have to be superuser and postgres/postgis extentions with their devel header have to be installed. If you do not want Odoo to connect with a super user you can manually prepare your database. To do thisopen a client to your database using a super user and run: \nCREATE EXTENSION postgis;\nCREATE EXTENSION postgis_topology;\n', None)
2019-08-16 23:33:42,957 14 CRITICAL datensas-fieldservice11-app-fieldservice-stock-538725 odoo.service.server: Failed to initialize database `datensas-fieldservice11-app-fieldservice-stock-538725`.
Traceback (most recent call last):
File "/home/odoo/src/user/base_geoengine/geo_db.py", line 32, in init_postgis
""")
File "/home/odoo/src/odoo/odoo/sql_db.py", line 155, in wrapper
return f(self, *args, **kwargs)
File "/home/odoo/src/odoo/odoo/sql_db.py", line 232, in execute
res = self._obj.execute(query, params)
psycopg2.OperationalError: could not open extension control file "/usr/share/postgresql/10/extension/postgis.control": No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/odoo/src/odoo/odoo/service/server.py", line 1006, in preload_registries
registry = Registry.new(dbname, update_module=update_module)
File "/home/odoo/src/odoo/odoo/modules/registry.py", line 85, in new
odoo.modules.load_modules(registry._db, force_demo, status, update_module)
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 380, in load_modules
loaded_modules, update_module, models_to_check)
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
perform_checks=perform_checks, models_to_check=models_to_check
File "/home/odoo/src/odoo/odoo/modules/loading.py", line 144, in load_module_graph
getattr(py_module, pre_init)(cr)
File "/home/odoo/src/user/base_geoengine/geo_db.py", line 35, in init_postgis
"Error, can not automatically initialize spatial postgis support. "
odoo.exceptions.MissingError: ('Error, can not automatically initialize spatial postgis support. Database user may have to be superuser and postgres/postgis extentions with their devel header have to be installed. If you do not want Odoo to connect with a super user you can manually prepare your database. To do thisopen a client to your database using a super user and run: \nCREATE EXTENSION postgis;\nCREATE EXTENSION postgis_topology;\n', None)
2019-08-16 23:33:42,961 14 INFO datensas-fieldservice11-app-fieldservice-sto

**Comment by brian10048** [comment]
@datensas you will need to install PostGIS in order to use v11. It is not possible to install PostGIS on the odoo.sh platform.

You can use v12 field service without the geoengine on odoo.sh

**Comment by DatenSAS** [comment]
Thanks
