### ISSUE TITLE
Error when click on Field Service Button

### ISSUE THREAD

**Issue by fdesrosiers3** [OCA/field-service#328]
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/odoo/odoo-server/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/odoo/odoo-server/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/odoo/odoo-server/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1084, in postprocess_and_fields
    fields_def = self.postprocess(model, node, view_id, False, fields)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 909, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 909, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 909, in postprocess
    fields.update(self.postprocess(model, f, view_id, in_tree_view, model_fields))
  [Previous line repeated 1 more time]
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 869, in postprocess
    ).postprocess_and_fields(field.comodel_name, f, view_id)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1075, in postprocess_and_fields
    fields = Model.fields_get(None)
  File "/odoo/odoo-server/odoo/models.py", line 2679, in fields_get
    description = field.get_description(self.env)
  File "/odoo/odoo-server/odoo/fields.py", line 745, in get_description
    value = value(env)
  File "/odoo/odoo-server/odoo/fields.py", line 1925, in _description_selection
    return selection(env[self.model_name])
  File "/odoo/enterprise/addons/stock_request/models/stock_request.py", line 26, in _get_request_states
    return self.__get_request_states()
  File "/odoo/enterprise/addons/stock_request_submit/models/stock_request.py", line 14, in __get_request_states
    states.index(('draft', _('Draft'))) + 1,
ValueError: ('draft', 'Brouillon') is not in list

**Comment by bodedra** [comment]
@fdesrosiers3 I am not sure but seems issue has been fixed. Ref https://github.com/OCA/stock-logistics-warehouse/commit/48b0dc8222514218b0fd438805cc84b09932090a#diff-eb06c1073ddb2f4adebeebfe498f5e8b

Can you try with updated version?
