### ISSUE TITLE
Time line

### ISSUE THREAD

**Issue by ghost** [OCA/field-service#379]
after instalation of the Field service module in Odoo 12 the Project time line stopped working with the error: (the timeline of Field service working though) 
Uncaught TypeError: Cannot read property '_fieldId' of null
https://amevia.eu/web_timeline/static/lib/vis/vis-timeline-graph2d.min.js:35
Traceback:
TypeError: Cannot read property '_fieldId' of null
    at n._onAddItem (https://amevia.eu/web_timeline/static/lib/vis/vis-timeline-graph2d.min.js:35:20602)
    at Array.s (https://amevia.eu/web_timeline/static/lib/vis/vis-timeline-graph2d.min.js:28:12634)
    at Object.emit (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:129439)
    at lt.emit (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:127478)
    at lt.tryEmit (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:123217)
    at lt.recognize (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:123547)
    at Object.recognize (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:128441)
    at z.O [as callback] (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:112132)
    at z.handler (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:120058)
    at C.domHandler (https://amevia.eu/web/content/1074-5eca877/web.assets_backend.js:3072:111825)

How to fix it?

**Comment by brenoalef** [comment]
Project timeline stopped working for me too. I think it's because of the person filter added to the timeline header. I'm getting the following error:
File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 853, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'person_id' in leaf "<osv.ExtendedLeaf: ('person_id', 'in', [False]) on project_task (ctx: )>"

**Comment by brian10048** [comment]
I have not duplicated this error, but it seems the fieldservice timeline is interfering with the project timeline

@smangukiya Do you have any thoughts on this? 
cc:@max3903

**Comment by brenoalef** [comment]
Any news on this?

**Comment by falexandresilva** [comment]
Hi, I have the same problem reported by @brenoalef . Any solution to solve or workaround this problem?

**Comment by falexandresilva** [comment]
http://3416819-12-0-e1c9ce.runbot2.odoo-community.org/web/login 
 I've tested on runbot and the error happens. On the original runbot are'nt installed the project timeline. When I install project timeline and go to tasks / view timeline the error appears. Someone can verify?

**Comment by JordiADARIA** [comment]
Yes! its happening o runbot and with fresh or "used" databases.



> Project timeline stopped working for me too. I think it's because of the person filter added to the timeline header. I'm getting the following error:
> File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 853, in parse
> raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
> ValueError: Invalid field 'person_id' in leaf "<osv.ExtendedLeaf: ('person_id', 'in', [False]) on project_task (ctx: )>"

Yes, ive the same problem, ive tested it even on fresh database installations and its happening the same: installs project, installs project_timeline, all it's ok... BUT installs Field Service, and then all timeline views are returning errors, model property undefined, invalid field "person_id".... i'm trying to solve it.

**Comment by JordiADARIA** [comment]
from runbot:
Odoo Server Error
Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/.repo_requirements/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/odoo-12.0/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/.repo_requirements/odoo/odoo/api.py", line 728, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/.repo_requirements/odoo/odoo/models.py", line 4595, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/.repo_requirements/odoo/odoo/models.py", line 1579, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/.repo_requirements/odoo/odoo/models.py", line 4127, in _search
    query = self._where_calc(args)
  File "/.repo_requirements/odoo/odoo/models.py", line 3919, in _where_calc
    e = expression.expression(domain, self)
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 673, in __init__
    self.parse()
  File "/.repo_requirements/odoo/odoo/osv/expression.py", line 854, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'person_id' in leaf "<osv.ExtendedLeaf: ('person_id', 'in', [False]) on project_project (ctx: )>"

**Comment by JordiADARIA** [comment]
the problem could be located at this area:

[https://github.com/OCA/field-service/tree/12.0/fieldservice/static/src](url)

**Comment by brian10048** [comment]
I think this may be fixed with #739
