### ISSUE TITLE
Error at print service order

### ISSUE THREAD

**Issue by ghost** [OCA/field-service#560]
module: fieldservice
version: 12.0
Odoo Enterprise v12.0

**Steps to reproduce**
Button Print > Service Order
- ...

**Current behavior**

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 347, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_fieldservice_report_fsm_order_document_55276
  File "<template>", line 2, in body_call_content_55275
AttributeError: 'fsm.order' object has no attribute 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1671, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/opt/odoo/odoo-server/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 1612, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 712, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/opt/addons/addons-enterprise/web_studio/models/ir_actions_report.py", line 18, in render_qweb_html
    return super(IrActionsReport, self).render_qweb_html(docids, data)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 752, in render_qweb_html
    return self.render_template(self.report_name, data), 'html'
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 534, in render_template
    return view_obj.render_template(template, values)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1304, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 315, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 29, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 1313, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/addons/addons-enterprise/web_studio/models/ir_qweb.py", line 43, in render
    return super(IrQWeb, self).render(template, values=values, **options)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 349, in _compiled_fn
    raise e
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 347, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_4084_55262
  File "<template>", line 2, in body_call_content_55261
  File "<template>", line 3, in foreach_55260
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 354, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: 'fsm.order' object has no attribute 'state'
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/models/qweb.py", line 347, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_fieldservice_report_fsm_order_document_55276
  File "<template>", line 2, in body_call_content_55275
AttributeError: 'fsm.order' object has no attribute 'state'

Error to render compiling AST
AttributeError: 'fsm.order' object has no attribute 'state'
Template: fieldservice.report_fsm_order_document
Path: /templates/t/t/div[1]
Node: <div t-if="doc.date_end and doc.state.is_closed" class="col-xs-3">
                <strong>Fecha Completada:</strong>
                <p t-field="doc.date_end"/>
            </div>
            

**Expected behavior**

Print service order in pdf file

**Comment by brian10048** [comment]
@over-garcia 

Please check that you have the most recent fieldservice code.

This issue was recently fixed with this [commit](https://github.com/OCA/field-service/commit/20d35f66e1699bdaa3a3fe33c5afb69008e6a235)
