### ISSUE TITLE
Cannot create a Maintenance Request for FS Equipment from Odoo Maintenance.

### ISSUE THREAD

**Issue by felixsniper** [OCA/field-service#634]
Hi OCA, 

I am using Odoo V12 Community.

I cannot create a Maintenance Request for FS Equipment from Odoo Maintenance. Please help give me an advice.

Step to Reproduce:
1) Create an FS Equipment "Blue Desk" from Field Service App.
2) Go to Maintenance -> Equipments -> Select "Blue Desk".
3) Create an Maintenance Ticket for FS Equipment "Blue Desk" | Failed
=> An error box pop up.

Thanks, 
Felix.

Please help refer to the photos and error log as below:
![image](https://user-images.githubusercontent.com/69030714/92716596-3ac0bb80-f389-11ea-9edb-eedb5879077b.png)
![image](https://user-images.githubusercontent.com/69030714/92716648-49a76e00-f389-11ea-9f40-7126dff8c0ca.png)

Error Log:
```
 Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 757, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 737, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-336>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/maintenance_project/models/maintenance_request.py", line 21, in create
    newreq = super().create(values)
  File "<decorator-gen-294>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/fieldservice_maintenance/models/maintenance_request.py", line 27, in create
    'request_id': request.id
  File "<decorator-gen-432>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/base_automation/models/base_automation.py", line 228, in create
    records = create.origin(self.with_env(actions.env), vals_list, **kw)
  File "<decorator-gen-402>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/addons/fieldservice_route_vehicle/models/fsm_order.py", line 34, in create
    return super().create(vals)
  File "<decorator-gen-299>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/fieldservice_vehicle/models/fsm_order.py", line 21, in create
    return super().create(vals)
  File "<decorator-gen-298>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/fieldservice_route/models/fsm_order.py", line 87, in create
    return super().create(vals)
  File "<decorator-gen-293>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/fieldservice_maintenance/models/fsm_order.py", line 17, in create
    order = super(FSMOrder, self).create(vals)
  File "<decorator-gen-186>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/fieldservice/models/fsm_order.py", line 243, in create
    return super(FSMOrder, self).create(vals)
  File "<decorator-gen-119>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 272, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3588, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3688, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.DataError: invalid input syntax for integer: "maintenance"
LINE 1: ... 18, 'draft', NULL, 10, NULL, NULL, 0.0, 1, 1, 1, 'maintenan...
```

**Comment by marcelsavegnago** [comment]
Hi @felixnguyen-epiklah 
See if your version is up to date.

If I'm not mistaken this PR corrects that error.
https://github.com/OCA/field-service/pull/582

**Comment by felixsniper** [comment]
Hi @marcelsavegnago,
Thank you for you feedback,

**Testing Enviroment:**
+ Odoo CE V12 (From Odoo Official)
+ Field Service - v.12.0.2.12.1
+ Field Service - Stage Server Action v.12.0.2.0.0
+ Field Service - Maintenance v.12.0.1.1.0
=> This issue still happened

I downloaded all Field Service Apps/Add-ons from Odoo App Store.
Is there anything else that I need to check?

Thanks & Regards,
Felix

**Comment by marcelsavegnago** [comment]
hi @felixnguyen-epiklah normally, i am prefer clone the git repository.

This PR #635 fix integration between field service and maintenance. But, this OR have state approved but not merged yet

You can clone the field service repository and merge this PR into it.

**Comment by felixsniper** [comment]
Hi @marcelsavegnago,

It worked after merging the PR #580 to current Git Repository.
Thank you for your help.

Have a nice working day,
Thanks & Regards,
Felix Nguyen.

**Comment by marcelsavegnago** [comment]
Hi @felixnguyen-epiklah,

You can help by reviewing the PR.

**Comment by felixsniper** [comment]
Hi @marcelsavegnago,

I already reviewed the PR #580.

Thanks,
Felix Nguyen.
