### ISSUE TITLE
problem select location on recurring order

### ISSUE THREAD

**Issue by babatoko** [OCA/field-service#637]
Hi,

Have got this issue when creating a recurring order.

It rise when I want to select location.

Error:
Uncaught TypeError: value.split is not a function

https://www.entretien-maconnais.fr/web/content/22187-dbe1c81/web.assets_backend.js:1213
Traceback:
TypeError: value.split is not a function
    at Class._getDisplayName (https://www.entretien-maconnais.fr/web/content/22187-dbe1c81/web.assets_backend.js:1213:101)
    at https://www.entretien-maconnais.fr/web/content/22187-dbe1c81/web.assets_backend.js:1218:219
    at Function._.map._.collect (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:13:270)
    at Object.<anonymous> (https://www.entretien-maconnais.fr/web/content/22187-dbe1c81/web.assets_backend.js:1218:186)
    at Object.<anonymous> (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:802:681)
    at fire (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:796:299)
    at Object.fireWith [as resolveWith] (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:801:198)
    at Object.deferred.<computed> [as resolve] (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:803:56)
    at Object.<anonymous> (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:3589:448)
    at Object.<anonymous> (https://www.entretien-maconnais.fr/web/content/22119-2c1cc86/web.assets_common.js:802:681)

I haven't tested on runbot.

**Comment by babatoko** [comment]
I can see on my setup is that the location name is not set correctly.

**Comment by babatoko** [comment]
Problem have been solved by clearing web browser cache

**Comment by babatoko** [comment]
Problem have been solved by clearing web browser cache
