### ISSUE TITLE
geospatial for odoo 11

### ISSUE THREAD

**Issue by jesulo** [OCA/field-service#82]
Hi, 

For odoo 11 there is no base_geoengine module, right? because I have not found in

Please refer to the installation instructions available at: https://github.com/OCA/geospatial/tree/11.0/base_geoengine

Regards,

**Comment by tate11** [comment]
https://github.com/OCA/geospatial/pull/178

**Comment by jesulo** [comment]
Thanks @tate11,
yes is in https://github.com/OCA/geospatial/tree/17b429442bc53b03473d347f91f593a0f9be41ad

I have an error, of record

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 3450, in _create
    self._check_selection_field_value(name, val)
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 2104, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/user99/Developments/odoo11/odoo/odoo/fields.py", line 1808, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for geoengine.vector.layer.classification: 'custom'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 3450, in _create
    self._check_selection_field_value(name, val)
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 2104, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/user99/Developments/odoo11/odoo/odoo/fields.py", line 1808, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
odoo.tools.convert.ParseError: "Wrong value for geoengine.vector.layer.classification: 'custom'" while parsing /home/user99/Developments/odoo11/extra-addons/field-service-11.0/fieldservice/views/fsm_order.xml:373, near
<record id="geoengine_vector_layer_fsmordertatecoloredcustom0" model="geoengine.vector.layer">
      <field name="geo_field_id" ref="fieldservice.field_fsm_order_shape"/>
      <field name="name">FSM Order State colored custom</field>
      <field name="classification">custom</field>
      <field eval="6" name="sequence"/>
      <field name="view_id" ref="ir_ui_view_fsm_order_map"/>
      <field name="geo_repr">colored</field>
      <field eval="1" name="nb_class"/>
      <field name="attribute_field_id" ref="fieldservice.field_fsm_order_custom_color"/>
      <field name="begin_color">#FFFFFF</field>
    </record>

**Comment by max3903** [comment]
Until base_geoengine gets merged, please use the pvm branch from https://github.com/ursais/geospatial/
