### ISSUE TITLE
Fieldservice_equipment_stock error on stock move action confirm #829

### ISSUE THREAD

**Issue by castalie-dev** [OCA/field-service#831]
1. Install module Fieldservice_equipment_stock
2. Validate a stock.picking IN movement and you will get that error
[Video record link](https://recordit.co/1ZvemJLbL1)

```

  File "/opt/odoo/addons/stock/wizard/stock_immediate_transfer.py", line 65, in process
    return pickings_to_validate.with_context(skip_immediate=True).button_validate()
  File "/opt/odoo/addons/stock/models/stock_picking.py", line 943, in button_validate
    pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
  File "/opt/odoo/addons/sale_stock/models/stock.py", line 78, in _action_done
    res = super()._action_done()
  File "/opt/odoo/addons/stock/models/stock_picking.py", line 763, in _action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/opt/odoo-addons/field-service/fieldservice_equipment_stock/models/stock_move.py", line 29, in _action_done
    vals = self.prepare_equipment_values(line)
  File "/opt/odoo-addons/field-service/fieldservice_equipment_stock/models/stock_move.py", line 15, in prepare_equipment_values
    "location_id": move.stock_request_ids.fsm_order_id.location_id.id,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'stock.move' object has no attribute 'stock_request_ids'
```

**Comment by aymenrahmay** [comment]
Hello, 

After pulling the updated branch, still we are facing an issue by clicking the validate button on the stock.picking
```
Erreur:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/stock/wizard/stock_immediate_transfer.py", line 65, in process
    return pickings_to_validate.with_context(skip_immediate=True).button_validate()
  File "/opt/odoo/addons/stock/models/stock_picking.py", line 943, in button_validate
    pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
  File "/opt/odoo/addons/sale_stock/models/stock.py", line 78, in _action_done
    res = super()._action_done()
  File "/opt/odoo/addons/stock/models/stock_picking.py", line 763, in _action_done
    todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
  File "/opt/odoo-addons/field-service/fieldservice_equipment_stock/models/stock_move.py", line 29, in _action_done
    vals = self.prepare_equipment_values(line)
  File "/opt/odoo-addons/field-service/fieldservice_equipment_stock/models/stock_move.py", line 15, in prepare_equipment_values
    "location_id": move.stock_request_ids.fsm_order_id.location_id.id,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'stock.move' object has no attribute 'stock_request_ids'  
```

**Comment by smangukiya** [comment]
> Hello,
> 
> After pulling the updated branch, still we are facing an issue by clicking the validate button on the stock.picking
> 
> ```
> Erreur:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
>     result = request.dispatch()
>   File "/opt/odoo/odoo/http.py", line 684, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo/http.py", line 360, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo/http.py", line 348, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo/http.py", line 913, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo/http.py", line 532, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/addons/web/controllers/main.py", line 1393, in call_button
>     action = self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 396, in call_kw
>     result = _call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/odoo/api.py", line 383, in _call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/addons/stock/wizard/stock_immediate_transfer.py", line 65, in process
>     return pickings_to_validate.with_context(skip_immediate=True).button_validate()
>   File "/opt/odoo/addons/stock/models/stock_picking.py", line 943, in button_validate
>     pickings_to_backorder.with_context(cancel_backorder=False)._action_done()
>   File "/opt/odoo/addons/sale_stock/models/stock.py", line 78, in _action_done
>     res = super()._action_done()
>   File "/opt/odoo/addons/stock/models/stock_picking.py", line 763, in _action_done
>     todo_moves._action_done(cancel_backorder=self.env.context.get('cancel_backorder'))
>   File "/opt/odoo-addons/field-service/fieldservice_equipment_stock/models/stock_move.py", line 29, in _action_done
>     vals = self.prepare_equipment_values(line)
>   File "/opt/odoo-addons/field-service/fieldservice_equipment_stock/models/stock_move.py", line 15, in prepare_equipment_values
>     "location_id": move.stock_request_ids.fsm_order_id.location_id.id,
> Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo/http.py", line 640, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo/http.py", line 316, in _handle_exception
>     raise exception.with_traceback(None) from new_cause
> AttributeError: 'stock.move' object has no attribute 'stock_request_ids'  
> ```

@aymenrahmay : Yes we are working on it here https://github.com/OCA/field-service/pull/833. Thanks

**Comment by jbjour** [comment]
Hello do you have any update on the issue ? 
Thanks
