### ISSUE TITLE
Problems uninstalling Fieldservice and Fieldservice maintanance. 

### ISSUE THREAD

**Issue by zionram** [OCA/field-service#840]
Hi, I'm newer to the Odoo scene. I ordered a managed server and I asked to install the field service along with various add-ons. However, once this was done I started getting errors on the field service module. Then it didn't work altogether. So I attempted to uninstall everything and start over.  It worked for all but 2 modules, the "fieldservice" app and the "fieldservice_maintenance" app. 

When I attempt to uninstall the field service app, I run into this problem. 

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo14ce/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14ce/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14ce/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14ce/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14ce/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14ce/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14ce/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14ce/addons/web/controllers/main.py", line 1389, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14ce/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14ce/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14ce/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14ce/odoo/models.py", line 6254, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "/opt/odoo14ce/odoo/models.py", line 6045, in __init__
    self.fetch(name)
  File "/opt/odoo14ce/odoo/models.py", line 6053, in fetch
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/opt/odoo14ce/odoo/models.py", line 6053, in <listcomp>
    self[name] = [Snapshot(line, tree[name]) for line in record[name]]
  File "/opt/odoo14ce/odoo/models.py", line 6045, in __init__
    self.fetch(name)
  File "/opt/odoo14ce/odoo/models.py", line 6055, in fetch
    self[name] = record[name]
  File "/opt/odoo14ce/odoo/models.py", line 5662, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo14ce/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/opt/odoo14ce/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo14ce/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
  File "/opt/odoo14ce/odoo/addons/base/models/ir_model.py", line 203, in _compute_count
    records = self.env[model.model]
  File "/opt/odoo14ce/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/opt/odoo14ce/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14ce/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)

  File "/opt/odoo14ce/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'fsm.equipment'

**Comment by zionram** [comment]
Another thing I noticed that was wierd. There seems to two "Field Service -  Accounting" modules ,  and I think there used to be a "field service" module that wasn't accounting, and that seems to have disappeared.  Is it possible it somehow adopted the wrong folder? That sounds crazy, but I don't understand it.

**Comment by zionram** [comment]
Upon further diagnosis of my issue. After comparing the fieldservice and fieldservice_account code base that is on your Odoo server I noticed they are the same which is why I was getting that error.
