### ISSUE TITLE
Error reinstall fieldservice

### ISSUE THREAD

**Issue by jesulo** [OCA/field-service#86]
Hi,

when I install again I get this error, how could I fix it? odoo 11

Traceback (most recent call last):
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/home/user99/Developments/odoo11/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/web/controllers/main.py", line 935, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/web/controllers/main.py", line 923, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-41>", line 2, in button_immediate_install
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/module/module.py", line 448, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/module/module.py", line 541, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/home/user99/Developments/odoo11/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 751, in parse
    exc_info[2]
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/tools/convert.py", line 654, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/user99/Developments/odoo11/odoo/odoo/addons/base/ir/ir_model.py", line 1476, in _update
    record = record.create(values)
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 3372, in create
    record = self.browse(self._create(old_vals))
  File "/home/user99/Developments/odoo11/odoo/odoo/models.py", line 3465, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/home/user99/Developments/odoo11/odoo/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/home/user99/Developments/odoo11/odoo/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "insert or update on table "geoengine_vector_layer" violates foreign key constraint "geoengine_vector_layer_geo_field_id_fkey"
DETAIL:  Key (geo_field_id)=(21207) is not present in table "ir_model_fields".
" while parsing /home/user99/Developments/odoo11/extra-addons/field-service-11.0/fieldservice/views/fsm_order.xml:361, near
record id="geoengine_vector_layer_fsm0" model="geoengine.vector.layer">
       field name="geo_field_id" ref="fieldservice.field_fsm_order_shape"/>
        field name="name">FSM Order Point</field>
        field name="classification">unique</field>
        field eval="6" name="sequence"/>
        field name="view_id" ref="ir_ui_view_fsm_order_map"/>
        field name="geo_repr">colored</field>
        field eval="1" name="nb_class"/>
        field name="attribute_field_id" ref="fieldservice.field_fsm_order_stage_name"/>
        field name="begin_color">#0AFF68</field>
    </record>

**Comment by max3903** [comment]
Duplicates of #82
