### ISSUE TITLE
Error installing field-service -  missing 1 required positional argument: 'partial'

### ISSUE THREAD

**Issue by jamesln92** [OCA/field-service#87]
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/james/workspace/odoo_v11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/james/workspace/odoo_v11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/home/james/workspace/odoo_v11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/james/workspace/odoo_v11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/james/workspace/odoo_v11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/james/workspace/odoo_v11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/james/workspace/odoo_v11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/home/james/workspace/odoo_v11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/james/workspace/odoo_v11/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/james/workspace/odoo_v11/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/james/workspace/odoo_v11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/james/workspace/odoo_v11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/james/workspace/odoo_v11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/james/workspace/odoo_v11/odoo/modules/loading.py", line 152, in load_module_graph
    registry.setup_models(cr)
  File "/home/james/workspace/odoo_v11/odoo/modules/registry.py", line 277, in setup_models
    model._setup_fields()
TypeError: _setup_fields() missing 1 required positional argument: 'partial'

**Comment by max3903** [comment]
@jamesln92 Can you check again with the latest version please?

**Comment by jigneshjarsaniya** [comment]
@max3903 , I'm getting same issue with latest version as well.

**Comment by bodedra** [comment]
@jamesln92 @jigneshjarsaniya 

Can you replace your _'base_geoengine'_ module with these URL. https://github.com/asaunier/geospatial/tree/geoengine_reworked

**Comment by jigneshjarsaniya** [comment]
@bodedra , I tried it but there is an error with that module as well. 

> <record id="geoengine_vector_layer_fsmordertatecoloredcustom0" model="geoengine.vector.layer">
      <field name="geo_field_id" ref="fieldservice.field_fsm_order_shape"/>
      <field name="name">FSM Order State colored custom</field>
      <field name="classification">custom</field>
      <field eval="6" name="sequence"/>
      <field name="view_id" ref="ir_ui_view_fsm_order_map"/>
      <field name="geo_repr">colored</field>
      <field eval="1" name="nb_class"/>
      <field name="attribute_field_id" ref="fieldservice.field_fsm_order_custom_color"/>
      <field name="begin_color">#FFFFFF</field>
    </record>
> 2019-01-10 07:01:40,870 15797 ERROR field_service odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/jignesh/workspace/odoo-server/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/jignesh/workspace/odoo-server/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/home/jignesh/workspace/odoo-server/odoo/addons/base/ir/ir_model.py", line 1470, in _update
    record = record.create(values)
  File "/home/jignesh/workspace/odoo-server/odoo/models.py", line 3294, in create
    record = self.browse(self._create(old_vals))
  File "/home/jignesh/workspace/odoo-server/odoo/models.py", line 3372, in _create
    self._check_selection_field_value(name, val)
  File "/home/jignesh/workspace/odoo-server/odoo/models.py", line 2039, in _check_selection_field_value
    field.convert_to_cache(value, self)
  File "/home/jignesh/workspace/odoo-server/odoo/fields.py", line 1798, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for geoengine.vector.layer.classification: 'custom'

**Comment by bodedra** [comment]
Yes. You need to wait or you may review at https://github.com/asaunier/geospatial/pull/1 Once that PR will be merged, no longer error will be face.
