### ISSUE TITLE
Odoo 14 - Error's in during the execution of unit test's on Odoo sh and in the local 

### ISSUE THREAD

**Issue by aymenrahmay** [OCA/field-service#885]
Odoo V14 (Entreprise)

After installing some FSM modules we got this error 
```

**odoo.exceptions.AccessError: You are not allowed to access 'Field Service Location' (fsm.location) records.

This operation is allowed for the following groups:
	- Field Service/Dispatcher
	- Field Service/User (only own documents)

Contact your administrator to request access if necessary.**
```

Full log details:

```
ERROR: Subtest TestLeadMerge.test_lead_merge_mixed (login='user_sales_manager')
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.access', <function IrModelAccess.check at 0x7f8d0c97e940>, 174, False, 'fsm.location', 'read', True, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tests/common.py", line 1472, in wrapper
    func(*args, **kwargs)
  File "/home/odoo/src/odoo/addons/crm/tests/test_crm_lead_merge.py", line 131, in test_lead_merge_mixed
    result = merge.action_merge()
  File "/home/odoo/src/odoo/addons/crm/wizard/crm_merge_opportunities.py", line 43, in action_merge
    merge_opportunity = self.opportunity_ids.merge_opportunity(self.user_id.id, self.team_id.id)
  File "/home/odoo/src/odoo/addons/crm/models/crm_lead.py", line 1143, in merge_opportunity
    opportunities_head.write(merged_data)
  File "/home/odoo/src/odoo/addons/crm/models/crm_lead.py", line 598, in write
    write_result = super(Lead, self).write(vals)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/addons/mail/models/mail_activity.py", line 788, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 3704, in write
    fields[0].determine_inverse(real_recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1187, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/addons/crm/models/crm_lead.py", line 357, in _inverse_email_from
    lead.partner_id.email = lead.email_from
  File "/home/odoo/src/odoo/odoo/fields.py", line 1129, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/src/odoo/addons/snailmail/models/res_partner.py", line 26, in write
    return super(ResPartner, self).write(vals)
  File "/home/odoo/src/odoo/addons/partner_autocomplete/models/res_partner.py", line 199, in write
    res = super(ResPartner, self).write(values)
  File "/home/odoo/src/user/extra_oca/field-service/fieldservice/models/res_partner.py", line 74, in write
    self._convert_fsm_location()
  File "/home/odoo/src/user/extra_oca/field-service/fieldservice/models/res_partner.py", line 61, in _convert_fsm_location
    self.env["fsm.location"]
  File "/home/odoo/src/odoo/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/odoo/models.py", line 4494, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/odoo/models.py", line 3332, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-33>", line 2, in check
  File "/home/odoo/src/odoo/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_model.py", line 1805, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to access 'Field Service Location' (fsm.location) records.

This operation is allowed for the following groups:
	- Field Service/Dispatcher
	- Field Service/User (only own documents)

Contact your administrator to request access if necessary.
```

**Comment by jbjour** [comment]
Hello, 
I am also getting this issue has anyone an update about this ?

Thanks
